### ISSUE TITLE
Set `termguicolors` within Tundra

### ISSUE THREAD

**Issue by mattjamesdev** [sam4llis/nvim-tundra#5] opened 2022-09-10 06:34 UTC
I noticed other colourscheme plugins set `termguicolors` within their plugin, whereas this one doesn't. This causes the colourscheme to not be applied properly if `termguicolors` is not set explicitly by the user elsewhere in their config.

Setting the colourscheme on its own (everything is blank):
<img width="343" alt="Screen Shot 2022-09-10 at 4 07 46 pm" src="https://user-images.githubusercontent.com/57205718/189471558-2b5bff22-5628-4899-ba8e-3ebe842be419.png">

After entering `:set termguicolors`:
<img width="343" alt="Screen Shot 2022-09-10 at 4 07 58 pm" src="https://user-images.githubusercontent.com/57205718/189471578-5157a465-28ef-449d-b572-27f78c99712a.png">

Based on what I've seen in other colourschemes' "init.lua"s, I think it should be as simple as adding the line `vim.opt.termguicolors = true` somewhere in the `M.load` function of `lua/nvim-tundra/init.lua`.

**Comment by sam4llis** [comment] 2022-09-10 12:29
Nice, this should be relatively easy to implement (and I’ll probably sort it out this weekend). Thanks for bringing this to my attention :)

**Comment by sam4llis** [comment] 2022-09-11 15:58
Commit 2182bed in the `dev` branch adds the suggested `vim.opt.termguicolors = true` to the colorscheme. I decided to add it externally from the `M.load` function in `colors/tundra.lua` as I want `M.load` to be specifically for applying or reloading highlight groups. I'll leave it a couple of days before merging to `main` and closing the issue to check it works as intended :)

**Comment by mattjamesdev** [comment] 2022-09-12 01:06
Awesome, thanks for looking into it!

**Comment by sam4llis** [comment] 2022-09-13 18:35
Cherry picked commit (from 2182bed)  e08d397 into main branch. Users don't need to set `termguicolors` to `true` in their Neovim configuration any longer :)

**Closed as completed** 2022-09-13 18:36 UTC
Labels: bug
