### ISSUE TITLE
Add support for dimming inactive splits

### ISSUE THREAD

**Issue by vihu** [sam4llis/nvim-tundra#3] opened 2022-09-09 22:17 UTC
It would be nice to add a configuration like `dim_inactive = true` for inactive split buffers.

**Comment by sam4llis** [comment] 2022-09-10 12:37
I’ll definitely have a look at implementing this functionality :)

**Comment by sam4llis** [comment] 2022-09-10 18:04
Commit cf0c85d  on the `dev` branch adds a way of dimming inactive windows. It adds the option `dim_inactive_windows` which can be opted in from a users `setup()` function. For example:

```lua
require('nvim-tundra').setup({
  -- ...
  dim_inactive_windows = {
    enabled = true,
    color = nil,
  },
  -- ...
}
```

The `colour` key can be used to override the default dimmed colour using colours from the tundra colour palette, or a hex value. As an example, using Tundras colour palette to overwrite the default 'dimmed' colour to `gray._800`:

```lua
require('nvim-tundra').setup({
  -- ...
  dim_inactive_windows = {
    enabled = true,
    color = require('nvim-tundra.palette.arctic').gray._800,
  },
  -- ...
}
```

Or, specifying a hexadecimal colour value:

```lua
require('nvim-tundra').setup({
  -- ...
  dim_inactive_windows = {
    enabled = true,
    color = '#FFFFFF', -- Dimmed to pure white.
  },
  -- ...
}
```

Let me know your thoughts on this :)

**Comment by vihu** [comment] 2022-09-10 21:06
This looks good to me and it does appear to work locally.

**Comment by sam4llis** [comment] 2022-09-10 22:16
Commit a761f38 on the `dev` branch allows the `dim_inactive_windows.enabled` boolean to  toggle as intended.

**Comment by sam4llis** [comment] 2022-09-10 22:22
One thing that also might be worth noting is the way that `dim_inactive_windows` option interacts with the `transparent_background` option. It's easily interchangeable but it'd be good to get your thoughts on the functionality if you use before merging with any stable branch.

The functionality is (a - current functionality) `dim_inactive_windows` takes precedence over `transparent_background` or (b) `transparent_background` takes precedence over `dim_inactive_windows`.  The latter method will effectively disable dimming if `transparent_background` is `true`. 

**(a)**

<img width="1321" alt="Screenshot 2022-09-10 at 22 52 40" src="https://user-images.githubusercontent.com/43378933/189502986-45d862e0-d01a-4963-bbd5-b6189423fec8.png">

**(b)**

<img width="1338" alt="Screenshot 2022-09-10 at 23 20 44" src="https://user-images.githubusercontent.com/43378933/189503673-5c19f68e-b269-4bcb-8b26-ddf42c73aded.png">

Let me know your thoughts on which action you'd prefer to happen - I'm leaning towards **(b)** as the default.

**Comment by vihu** [comment] 2022-09-10 23:01
Good point, I actually prefer option (a), since it has a clear distinction between active and inactive admittedly with the loss of transparency on the dimmed window (personally I think that's alright).

Here's kanagawa for example:

![image](https://user-images.githubusercontent.com/3199183/189504570-644f3656-e142-4edf-924a-6b9315864e55.png)

**Comment by sam4llis** [comment] 2022-09-11 10:46
Okay, I’ll keep option (a) for the functionality :) I’ll give it a couple of days (in case any edge cases have been missed) before rebasing and merging the dimming functionality into main.

**Comment by sam4llis** [comment] 2022-09-11 15:42
Commit 72ed02a on the `dev` branch adds `dim_inactive_windows` data to `README.md`.

**Comment by sam4llis** [comment] 2022-09-13 18:43
Rebased all commits related to this issue into commit 38dc96d on the `dev` branch.

**Comment by sam4llis** [comment] 2022-10-30 17:33
This has been working fine on the `dev` branch for Tundra for around a month. It's not documented yet, but I've included a simple way to toggle the dimmed view using `:Tundra toggle_dim` on the command line. I'm aiming to release `v0.2.0` of Tundra in the upcoming weeks, so this will be merged to `main` with documentation then!

**Closed as completed by sam4llis** 2022-10-30 17:33 UTC
Labels: enhancement
